### ISSUE TITLE
ERROR in app: Exception on /vultr/keys [POST]

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-adapter-libcloud#1]
During a server order, a user encountered the following error: 

```
[,665] ERROR in app: Exception on /vultr/keys [POST]
Traceback (most recent call last):
File "/data/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/data/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/data/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/data/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
if key.public_key == data['key']:
reraise(exc_type, exc_value, tb)
File "/data/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/data/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/data/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/nanobox_libcloud/controllers/keys.py", line 19, in key_create
result = adapter.do_key_create(request.headers, request.json)
File "/app/nanobox_libcloud/adapters/base.py", line 154, in do_key_create
AttributeError: 'SSHKey' object has no attribute 'public_key'
192.168.0.3 - - [12/Sep/2017:20:05:06 +0000] "POST /vultr/keys HTTP/1.1" 500 291 "-" "Faraday v0.9.2"
```

**Comment by danhunsaker** [comment]
Crap. I thought I'd prevented that one.

I'll have a fix up in a bit.

**Comment by danhunsaker** [comment]
There we go. Just missed a spot.
