### ISSUE TITLE
'SSHKey' object has no attribute 'fingerprint'

### ISSUE THREAD

**Issue by jedgalbraith** [nanobox-io/nanobox-adapter-libcloud#3]
This snippet if from the adapter-libcloud logs.

```
104.236.156.96 - - [06/Nov/2017:15:42:26 +0000] "GET /vultr/keys/nanobox-Platform-7a00a91a2a40 HTTP/1.1" 500 291 "-" "Faraday v0.9.2"
[,196] ERROR in app: Exception on /vultr/keys/nanobox-Platform-7a00a91a2a40 [GET]
Traceback (most recent call last):
File "/data/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/data/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/data/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/data/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/data/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/data/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/data/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/nanobox_libcloud/controllers/keys.py", line 38, in key_query
result = adapter.do_key_query(request.headers, key_id)
File "/app/nanobox_libcloud/adapters/base.py", line 187, in do_key_query
fingerprint=key.fingerprint
AttributeError: 'SSHKey' object has no attribute 'fingerprint'
```

**Comment by danhunsaker** [comment]
Should be working, now.
